services:
  - type: web
    name: pollaroid
    runtime: node
    buildCommand: yarn install && yarn build && yarn deploy-commands
    startCommand: yarn start
    plan: starter
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: pollaroid-db
          property: connectionString

databases:
  - name: pollaroid-db
    plan: basic-256mb
    databaseName: pollaroid
